import { RecordingExport } from './recording-export';
import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { RecordingProgress } from './recording-progress';
interface Channel { captureMode?:'source'|'pvw'; captionPid?:number; id:string; name:string; url:string; directory:string; enabled:boolean; codec:'h264'|'h265'|'copy'; format:'mp4'|'mkv'|'ts'; videoKbps:number; audioKbps:number; retentionDays:number; blockMinutes?:number; width:number; height:number; programId?:number; startAt?:string; endAt?:string; running?:boolean; error?:string; estimatedDayGB?:number }
interface Block { id:string; channelId:string; channel:string; start:string; end:string; bytes:number; codec:string; format:string }
const input='w-full bg-[#1a1f2e] border border-[#2a3050] rounded p-2 text-xs text-gray-200';
function ChannelForm({id,initial,onSaved,inputSource}:{id:string;initial?:Channel;onSaved:()=>void;inputSource:{name:string;url:string;programId?:number}}) {
  const [draft,setDraft]=useState<Channel>(initial ?? {id,name:`Canal ${id}`,url:'',directory:'D:\\DC-Censura\\Gravacoes',enabled:false,codec:'copy',format:'ts',videoKbps:384,audioKbps:64,retentionDays:30,blockMinutes:10,width:640,height:360});
  const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{setDraft(d=>d.enabled?d:{...d,...inputSource});},[inputSource.name,inputSource.url,inputSource.programId]);
  const [drives,setDrives]=useState<{DeviceID:string;VolumeName:string;FreeSpace:number}[]>([]);
  const scan=async()=>{try{const response=await fetch('/api/dispositivos/local-hardware');const data=await response.json();if(!response.ok||data.erro)throw new Error(data.erro||'Falha ao localizar HDs');setDrives(data.drives);}catch(error){setMessage(String(error));}};
  const field=(key:keyof Channel,value:any)=>setDraft(d=>({...d,[key]:value}));
  const save=async(enabled?:boolean)=>{const next=enabled===undefined?draft:{...draft,enabled,...(enabled?{startAt:undefined,endAt:undefined}:{})};setSaving(true);setMessage('');try{const response=await fetch(`/api/recordings/channels/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const data=await response.json();if(!response.ok)throw new Error(data.error);setDraft(next);setMessage('Configuração salva.');onSaved();}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setSaving(false);}};
  const dateValue=(value?:string)=>value?new Date(Date.parse(value)-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
  return <section className="border border-[#2a3050] rounded-lg p-3 space-y-3">
    <h3 className="font-semibold text-teal-300">Canal {id} · {initial?.running?'Gravando':'Parado / aguardando'}</h3>
    {initial?.error&&<p className="text-red-400 text-xs">{initial.error}</p>}
    <button type="button" className="text-xs text-teal-300 border border-teal-800 rounded px-3 py-2" onClick={()=>setDraft(d=>({...d,codec:'h265',format:'mp4',videoKbps:384,audioKbps:64,width:640,height:360,retentionDays:60,blockMinutes:2}))}>Perfil econômico · H.265 · 60 dias</button>
    <div className="grid grid-cols-2 gap-2 text-xs">
      <label className="col-span-2">O que gravar<select className={input} value={draft.captureMode??'source'} onChange={e=>{const captureMode=e.target.value as 'source'|'pvw';setDraft(d=>({...d,captureMode,...(captureMode==='pvw'&&d.codec==='copy'?{codec:'h264',format:'mp4'}:{})}));}}><option value="source">Fonte de entrada</option><option value="pvw">Vídeo do PVW + áudio + CC visível</option></select></label>
      <label>Codec de gravação<select className={input} value={draft.codec} onChange={e=>{const codec=e.target.value as Channel['codec'];setDraft(d=>({...d,codec,format:codec==='copy'?'ts':d.format==='ts'?'mp4':d.format}));}}>{draft.captureMode!=='pvw'&&<option value="copy">Original · BTS completo</option>}<option value="h264">H.264 · maior compatibilidade</option><option value="h265">H.265 · economia de espaço</option></select></label>
      <label>Formato<select className={input} value={draft.format} onChange={e=>field('format',e.target.value)}>{draft.codec==='copy'?<option value="ts">MPEG-TS original</option>:<><option value="mp4">MP4</option><option value="mkv">MKV</option></>}</select></label>
      {draft.codec!=='copy'&&<>
        <label>Resolução<select className={input} value={`${draft.width}x${draft.height}`} onChange={e=>{const [width,height]=e.target.value.split('x').map(Number);setDraft(d=>({...d,width,height}));}}>{[[640,360],[854,480],[1280,720],[1920,1080]].map(([w,h])=><option key={w} value={`${w}x${h}`}>{w} × {h}</option>)}</select></label>
        <label>Vídeo · kb/s<input className={input} type="number" min={128} max={12000} value={draft.videoKbps} onChange={e=>field('videoKbps',Number(e.target.value))}/></label>
        <label>Áudio · kb/s<input className={input} type="number" min={32} max={320} value={draft.audioKbps} onChange={e=>field('audioKbps',Number(e.target.value))}/></label>
        <p className="col-span-2 text-teal-300">Estimativa: {((draft.videoKbps+draft.audioKbps)*(draft.blockMinutes??10)*60/8000).toFixed(1)} MB/bloco · {((draft.videoKbps+draft.audioKbps)*86400/8000000).toFixed(1)} GB/dia · {((draft.videoKbps+draft.audioKbps)*86400/8000000*draft.retentionDays).toFixed(0)} GB em {draft.retentionDays} dias. Reserve também 10% do disco; o tamanho real varia.</p>
      </>}
      <label>Entrada selecionada<input className={input} value={draft.name} readOnly/></label>
      <label>Pasta / HD<input className={input} value={draft.directory} onChange={e=>field('directory',e.target.value)}/></label>
      <p className="col-span-2 text-gray-400">A entrada é definida ao iniciar a gravação. Para trocar, pare a gravação, escolha outra entrada e inicie novamente.</p>
      <label>Retenção · dias<input className={input} type="number" min={1} max={90} value={draft.retentionDays} onChange={e=>field('retentionDays',Number(e.target.value))}/></label>
      <label>Duração dos blocos<select className={input} value={draft.blockMinutes??2} onChange={e=>field('blockMinutes',Number(e.target.value))}>{[1,2,5,10].map(m=><option key={m} value={m}>{m} minuto(s)</option>)}</select></label>
      <label className="flex items-center gap-2"><input type="checkbox" checked={draft.enabled} onChange={e=>field('enabled',e.target.checked)}/>Ativar gravação automática</label>
      <label>Iniciar em (opcional)<input className={input} type="datetime-local" value={dateValue(draft.startAt)} onChange={e=>field('startAt',e.target.value?new Date(e.target.value).toISOString():undefined)}/></label>
      <label>Encerrar em (opcional)<input className={input} type="datetime-local" value={dateValue(draft.endAt)} onChange={e=>field('endAt',e.target.value?new Date(e.target.value).toISOString():undefined)}/></label>
    </div>
    <div className="flex gap-2 items-center text-xs"><button onClick={scan} className="text-teal-400">Localizar HDs</button>{drives.length>0&&<select aria-label={`HD do canal ${id}`} className={input} value="" onChange={e=>field('directory',`${e.target.value}\\DC-Censura\\Gravacoes`)}><option value="">Escolher HD</option>{drives.map(d=><option key={d.DeviceID} value={d.DeviceID}>{d.DeviceID} {d.VolumeName} · {(d.FreeSpace/1073741824).toFixed(1)} GB livres</option>)}</select>}</div>
    <p className="text-xs text-gray-400">{draft.codec==='copy'?'TS/BTS original preserva todos os PIDs, vídeos, áudios, tabelas, EPG e closed caption. O tamanho depende da taxa original da emissora.':'H.264/H.265 gravam vídeo e o primeiro áudio do programa selecionado, sem preservar tabelas, EPG e CC ARIB do BTS. Taxas menores reduzem tamanho e qualidade; H.265 exige mais processamento.'}</p>
    {draft.captureMode==='pvw'&&<p className="text-xs text-teal-300">Grava o vídeo do programa selecionado, o primeiro áudio e a legenda ARIB incorporada à imagem. Não grava botões ou painéis da interface. Mantenha o monitor aberto e o overlay de CC ativado: o texto exibido no PVW é incorporado ao arquivo.</p>}
    <p className="text-xs text-amber-300">Ao ativar, blocos antigos deste gravador serão apagados após {draft.retentionDays} dias ou para manter mais de 10% do disco livre. Outros arquivos do HD não são apagados.</p>
    <button disabled={saving} onClick={()=>void save()} className="bg-teal-800 rounded px-3 py-2 text-xs">{saving?'Salvando…':'Salvar canal'}</button><button disabled={saving||!inputSource.url} onClick={()=>void save(!(initial?.enabled))} className="ml-2 bg-red-800 disabled:opacity-40 rounded px-3 py-2 text-xs">{initial?.enabled?'Parar gravação':'Gravar agora'}</button><span className="text-xs ml-2">{message}</span>
  </section>;
}
export function MultichannelRecordings({open,onOpenChange,inputSource}:{open:boolean;onOpenChange:(open:boolean)=>void;inputSource:{name:string;url:string;programId?:number}}) {
  const [channels,setChannels]=useState<Channel[]|null>(null);const [files,setFiles]=useState<Block[]>([]);const [error,setError]=useState('');
  const [exportFile,setExportFile]=useState<string>();
  const [deleteIds,setDeleteIds]=useState<string[]>([]);const [deleting,setDeleting]=useState(false);
  const remove=async()=>{setDeleting(true);setError('');try{const response=await fetch('/api/recordings/files',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:deleteIds})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSelected(ids=>ids.filter(id=>!data.deleted.includes(id)));if(exportFile&&data.deleted.includes(exportFile))setExportFile(undefined);setDeleteIds([]);}catch(err){setError(String(err));}finally{await reload();setDeleting(false);}};
  const [serverTime,setServerTime]=useState<string>();
  const [channel,setChannel]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [selected,setSelected]=useState<string[]>([]);
  const reload=async()=>{try{const response=await fetch('/api/recordings');if(!response.ok)throw new Error('Não foi possível consultar o gravador.');const data=await response.json();setChannels(data.channels);setServerTime(data.serverTime);setFiles(data.files);}catch(err){setError(String(err));}};
  useEffect(()=>{if(!open)return;void reload();const timer=setInterval(()=>void reload(),5000);return()=>clearInterval(timer);},[open]);
  const found=files.filter(f=>(!channel||f.channelId===channel)&&(!from||Date.parse(f.end)>=new Date(from).getTime())&&(!to||Date.parse(f.start)<=new Date(to).getTime())).sort((a,b)=>Date.parse(b.start)-Date.parse(a.start));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-6xl max-h-[92vh] overflow-auto bg-[#0f1117] text-gray-200 border-[#2a3050]"><DialogHeader><DialogTitle>Gravação contínua · um canal</DialogTitle></DialogHeader>
    <p className="text-xs text-gray-400">Gravação em blocos de 1, 2, 5 ou 10 minutos, pastas por canal e dia, agendamento e exportação. O serviço continua na API quando esta janela é fechada.</p>
    {error&&<p className="text-red-400 text-sm">{error}</p>}
    {channels&&<div className="grid gap-3">{['1'].map(id=><ChannelForm key={id} id={id} initial={channels.find(c=>c.id===id)} onSaved={()=>void reload()} inputSource={inputSource}/>)}</div>}
    <RecordingProgress channels={channels??[]} serverTime={serverTime}/>
    {exportFile&&<RecordingExport key={exportFile} fileId={exportFile} selectedProgram={inputSource.programId}/>}<h3 className="text-teal-300 font-semibold">Busca e exportação</h3><p className="text-xs text-gray-400">{found.length} blocos encontrados · tabela com os 200 mais recentes · exportação até 500 blocos / 3,5 GB por ZIP.</p>
    <div className="grid sm:grid-cols-3 gap-2"><select aria-label="Canal da busca" className={input} value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Todas as gravações</option>{channels?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label className="text-xs">De<input className={input} type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs">Até<input className={input} type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
    <div className="flex gap-3 text-xs"><button onClick={()=>setSelected(found.slice(0,500).map(f=>f.id))}>Selecionar encontrados</button><button onClick={()=>setSelected([])}>Limpar seleção</button>
      <button disabled={!selected.length||deleting} className="text-red-400 disabled:opacity-40" onClick={()=>setDeleteIds(selected)}>Excluir selecionados · {selected.length}</button>
      <form action="/api/recordings/export" method="POST" target="_blank">{selected.map(id=><input key={id} type="hidden" name="ids" value={id}/>)}<button disabled={!selected.length} className="bg-teal-800 disabled:opacity-40 rounded px-3 py-1">Exportar ZIP · {selected.length} blocos</button></form>
    </div>
    {deleteIds.length>0&&<div role="alertdialog" aria-label="Confirmar exclusão" className="rounded border border-red-800 bg-red-950/40 p-3 text-sm space-y-2"><p>Apagar permanentemente {deleteIds.length} bloco(s) do HD? Esta ação não pode ser desfeita.</p><p className="text-xs text-gray-400">{(files.filter(f=>deleteIds.includes(f.id)).reduce((sum,f)=>sum+f.bytes,0)/1000000).toFixed(1)} MB selecionados. O bloco em gravação não é excluído.</p><div className="flex gap-3"><button disabled={deleting} onClick={()=>void remove()} className="rounded bg-red-700 px-3 py-2">{deleting?'Excluindo…':'Confirmar exclusão'}</button><button disabled={deleting} onClick={()=>setDeleteIds([])}>Cancelar</button></div></div>}
    <div className="max-h-72 overflow-auto"><table className="w-full text-xs"><thead><tr><th/><th>Canal</th><th>Início</th><th>Fim</th><th>Formato</th><th>MB</th><th>Exportação</th></tr></thead><tbody>{found.slice(0,200).map(f=><tr key={f.id} className="border-t border-[#2a3050]"><td><input type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,f.id]:ids.filter(id=>id!==f.id))}/></td><td>{f.channel}</td><td>{new Date(f.start).toLocaleString('pt-BR')}</td><td>{new Date(f.end).toLocaleString('pt-BR')}</td><td>{f.codec} / {f.format}</td><td>{(f.bytes/1000000).toFixed(1)}</td><td><a className="text-teal-400" href={`/api/recordings/files/${f.id}`}>Baixar</a> · <a className="text-teal-400" href={`/api/recordings/files/${f.id}/info`}>Informações BTS</a> · <button className="text-teal-400" onClick={()=>setExportFile(f.id)}>Converter</button> · <button disabled={deleting} className="text-red-400" onClick={()=>setDeleteIds([f.id])}>Excluir</button></td></tr>)}</tbody></table>{!found.length&&<p className="text-gray-500 p-3">Nenhum bloco finalizado neste período.</p>}</div>
  </DialogContent></Dialog>;
}
